### ISSUE TITLE
Current deployment is broken TypeError: Cannot read property 'slug' of undefined: 

### ISSUE THREAD

**Issue by benwinding** [romainlp/howtomakeanoffer#18]
![Screenshot from 2019-04-12 17-16-41](https://user-images.githubusercontent.com/11782590/56020765-0b96bc80-5d47-11e9-9506-774d1e81aacb.png)

**Comment by benwinding** [comment]
Looks great though! Love the transitions :smile:

**Comment by romainlp** [comment]
Fixed :)
