### ISSUE TITLE
Option for other bidding platforms: eBay, Craigslist

### ISSUE THREAD

**Issue by benwinding** [romainlp/howtomakeanoffer#3]
Would be cool to add a little dropdown for other online stores where bidding is a thing. Like:

- eBay (has 'make me an offer' button)
- Craigslist (mostly offers)

How can I contribute?! :)

**Comment by romainlp** [comment]
Welcome in the Howtomakeanoffer community @benwinding , all our team is pleased you find an interest in our revolutionary software.

Your are welcome to submit a pull request and our integration team will check it in a 5 business day delay.
